# ① PR承認時、即時or予約リリース判定
name: detect-release-type

on:
  pull_request_review:
    types: [submitted]

jobs:
  detect_release:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Check release.txt existence
        id: check_release
        run: |
          if [ -f ./release.txt ]; then
            echo "found=true" >> $GITHUB_OUTPUT
            echo "release_time=$(cat ./release.txt)" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Get PR branch name
        id: pr_branch
        run: |
          echo "pr_branch=${GITHUB_HEAD_REF:-${{ github.event.pull_request.head.ref }}}" >> $GITHUB_OUTPUT

      - name: Register EventBridge if scheduled
        if: steps.check_release.outputs.found == 'true'
        run: |
          aws events put-rule \
            --name "release-schedule-$(date +%s)" \
            --schedule-expression "at(${{ steps.check_release.outputs.release_time }})"

          aws events put-targets \
            --rule "release-schedule-$(date +%s)" \
            --targets "[{\"Id\":\"1\",\"Arn\":\"${{ secrets.LAMBDA_ARN }}\",\"Input\":\"{\\\"PR_BRANCH\\\":\\\"${{ steps.pr_branch.outputs.pr_branch }}\\\"}\"}]"

      - name: Trigger immediate deploy if no schedule
        if: steps.check_release.outputs.found == 'false'
        run: |
          gh workflow run main-merge.yml -f pr_branch=${{ steps.pr_branch.outputs.pr_branch }}
