# ✅ GitHub Actions: PR承認時にEventBridgeスケジュール予約

name: Schedule S3 deploy on PR approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  schedule-on-approval:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-1
      BUCKET_NAME: your-bucket-name
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read release time if exists
        id: read_release_time
        run: |
          if [ -f ./release_time.txt ]; then
            echo "found=true" >> $GITHUB_OUTPUT
            echo "value=$(cat ./release_time.txt)" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Schedule EventBridge if scheduled
        if: steps.read_release_time.outputs.found == 'true'
        run: |
          RULE_NAME=schedule-deploy-$(date +%s)
          SCHEDULE_TIME="${{ steps.read_release_time.outputs.value }}"
          aws events put-rule \
            --name "$RULE_NAME" \
            --schedule-expression "at($SCHEDULE_TIME)" \
            --region $AWS_REGION

          aws events put-targets \
            --rule "$RULE_NAME" \
            --targets "[{\"Id\":\"1\",\"Arn\":\"${{ secrets.LAMBDA_ARN }}\",\"Input\":\"{\\\"ref\\\":\\\"${{ github.event.pull_request.head.ref }}\\\"}\"}]" \
            --region $AWS_REGION

      - name: Log no-schedule fallback
        if: steps.read_release_time.outputs.found == 'false'
        run: echo "No release_time.txt found; skipping schedule."
