# ② PRをmainにマージする
name: main-merge

on:
  workflow_dispatch:
    inputs:
      pr_branch:
        description: 'Branch to merge (head branch name)'
        required: true

permissions:
  contents: write        # マージコミット作成に必要
  pull-requests: write   # PRのマージ操作に必要

jobs:
  merge_to_main:
    runs-on: ubuntu-latest

    # 検索など通常の gh 操作は GITHUB_TOKEN でOK
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Find PR number (open/base=main/head={input})
        id: pr
        shell: bash
        run: |
          set -euo pipefail
          BR="${{ github.event.inputs.pr_branch }}"
          PR_NUMBER=$(gh pr list -R "$GITHUB_REPOSITORY" \
            --state open --base main --head "$BR" \
            --json number -q '.[0].number' || true)

          if [[ -z "${PR_NUMBER:-}" ]]; then
            echo "::error ::No open PR found for head '$BR' targeting base 'main'."
            exit 1
          fi
          echo "pr_number=$PR_NUMBER" >> "$GITHUB_OUTPUT"

      - name: Merge PR into main (merge commit with PAT)
        # ← ここだけ PAT に切替（この push は人間/ボット名義になり on:push が起動）
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_MERGE }}   # ★リポのSecretsに作成しておく
        shell: bash
        run: |
          set -euo pipefail
          PR="${{ steps.pr.outputs.pr_number }}"
          gh pr merge -R "$GITHUB_REPOSITORY" "$PR" \
            --merge \
            --subject "CI: merge PR #$PR into main" \
            --body ""
          # もしブランチ保護の必須チェック待ちをしたいなら --auto も併用可:
          # gh pr merge -R "$GITHUB_REPOSITORY" "$PR" --merge --auto \
          #   --subject "CI: merge PR #$PR into main" --body ""
